import { FaAws } from 'react-icons/fa'
import {
  FaBolt,
  FaBucket,
  FaCloud,
  FaCode,
  FaCubes,
  FaDatabase,
  FaServer,
} from 'react-icons/fa6'
import {
  LuBrain,
  LuHandshake,
  LuTarget,
  LuTrendingUp,
  LuUsers,
} from 'react-icons/lu'
import {
  SiAngular,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiGit,
  SiGithubactions,
  SiGooglebigquery,
  SiGooglecloud,
  SiGooglecloudstorage,
  SiIonic,
  SiJest,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiOpenapiinitiative,
  SiPostman,
  SiReact,
  SiSelenium,
  SiTailwindcss,
  SiTypescript,
} from 'react-icons/si'

export const profileSkillIcons = {
  'Front-End & Mobile': [
    { label: 'React', Icon: SiReact, color: '#149ECA' },
    { label: 'Next.js', Icon: SiNextdotjs, color: '#111827' },
    { label: 'TypeScript', Icon: SiTypescript, color: '#3178C6' },
    { label: 'Angular', Icon: SiAngular, color: '#DD0031' },
    { label: 'Ionic', Icon: SiIonic, color: '#3880FF' },
    { label: 'Tailwind CSS', Icon: SiTailwindcss, color: '#06B6D4' },
  ],
  'Back-End & APIs': [
    { label: 'Node.js', Icon: SiNodedotjs, color: '#339933' },
    { label: 'Express', Icon: SiExpress, color: '#111827' },
    { label: 'OpenAPI', Icon: SiOpenapiinitiative, color: '#6BA539' },
    { label: 'Servidor', Icon: FaServer, color: '#2563EB' },
    { label: 'Microservicios', Icon: FaCubes, color: '#7C3AED' },
    { label: 'Arquitectura por eventos', Icon: FaBolt, color: '#F59E0B' },
  ],
  'AWS & Arquitectura Cloud': [
    { label: 'AWS', Icon: FaAws, color: '#FF9900' },
    { label: 'AWS Lambda', Icon: FaBolt, color: '#F59E0B' },
    { label: 'AWS CDK y API Gateway', Icon: FaCode, color: '#8B5CF6' },
    { label: 'DynamoDB', Icon: FaDatabase, color: '#4053D6' },
    { label: 'Amazon S3', Icon: FaBucket, color: '#3F8624' },
    { label: 'Servicios cloud', Icon: FaCloud, color: '#2563EB' },
  ],
  'Datos & Google Cloud': [
    { label: 'Google Cloud', Icon: SiGooglecloud, color: '#4285F4' },
    { label: 'MySQL', Icon: SiMysql, color: '#4479A1' },
    { label: 'MongoDB', Icon: SiMongodb, color: '#47A248' },
    { label: 'Firebase', Icon: SiFirebase, color: '#F59E0B' },
    { label: 'BigQuery', Icon: SiGooglebigquery, color: '#669DF6' },
    {
      label: 'Cloud Storage',
      Icon: SiGooglecloudstorage,
      color: '#4285F4',
    },
  ],
  'Calidad & Entrega': [
    { label: 'Git', Icon: SiGit, color: '#F05032' },
    { label: 'GitHub Actions', Icon: SiGithubactions, color: '#2088FF' },
    { label: 'Jest', Icon: SiJest, color: '#C21325' },
    { label: 'Postman', Icon: SiPostman, color: '#FF6C37' },
    { label: 'Selenium', Icon: SiSelenium, color: '#43B02A' },
    { label: 'Figma', Icon: SiFigma, color: '#A259FF' },
  ],
  'Habilidades Blandas': [
    { label: 'Trabajo colaborativo', Icon: LuHandshake, color: '#2563EB' },
    { label: 'Liderazgo técnico', Icon: LuUsers, color: '#7C3AED' },
    { label: 'Capacidad analítica', Icon: LuBrain, color: '#DB2777' },
    { label: 'Orientación a resultados', Icon: LuTarget, color: '#DC2626' },
    { label: 'Mejora continua', Icon: LuTrendingUp, color: '#059669' },
  ],
}
